<?php echo view('xu-element'); ?>
<?php echo view('xu-div'); ?>
<?php echo view('xu-button'); ?>
<?php echo view('xu-buttongroup'); ?>
<?php echo view('xu-toolbar'); ?>
<?php echo view('xu-label'); ?>
<?php echo view('xu-checkbox'); ?>
<?php echo view('xu-radio'); ?>
<?php echo view('xu-option'); ?>
<?php echo view('xu-select'); ?>
<?php echo view('xu-pager'); ?>
<?php echo view('xu-tablehead'); ?>
<?php echo view('xu-tablebody'); ?>
<?php echo view('xu-tablerow'); ?>
<?php echo view('xu-tableheadcell'); ?>
<?php echo view('xu-tablecell'); ?>
<?php echo view('xu-datatable'); ?>
<?php echo view('xu-toast-container'); ?>
<?php echo view('xu-toast'); ?>
